[project]
site_name = "Proyectos de inicio con Arduino"
site_description = "Proyectos sencillos para iniciarse con Arduino IDE y la placa EchidnaBlack2"
site_author = "Echidna Educación"
site_url = "https://echidnaeducacion.github.io/GuiaInicioArduinoIDE/"
copyright = "Contenido bajo licencia CC BY-SA 4.0"
docs_dir = "docs"
site_dir = "site"
extra_css = ["assets/stylesheets/extra.css"]
nav = [
  {"Inicio" = "index.md"},
  {"1. Introducción" = "01-introduccion.md"},
  {"2. Proyectos con Arduino" = [
    "02-arduino/index.md",
    {"2.1 Hola Mundo" = "02-arduino/01-hola-mundo.md"},
    {"2.2 Semáforo" = "02-arduino/02-semaforo.md"},
    {"2.3 Interruptor de luz" = "02-arduino/03-interruptor-de-luz.md"},
    {"2.4 Timbre" = "02-arduino/04-timbre.md"},
    {"2.5 Brillo LED" = "02-arduino/05-brillo-led.md"},
    {"2.6 Interruptor crepuscular" = "02-arduino/06-interruptor-crepuscular.md"},
    {"2.7 Piano de frutas" = "02-arduino/07-piano-de-frutas.md"},
    {"2.8 El echidna dice la temperatura" = "02-arduino/08-echidna-dice-temperatura.md"},
    {"2.9 Mezclamos colores" = "02-arduino/09-mezclamos-colores.md"},
    {"2.10 Vúmetro" = "02-arduino/10-vumetro.md"},
    {"2.11 Regulador de luz con joystick" = "02-arduino/11-regulador-de-luz.md"},
    {"2.12 Nivel de burbuja" = "02-arduino/12-nivel-de-burbuja.md"},
    {"2.13 Control desde el ordenador" = "02-arduino/13-control-desde-el-ordenador.md"}
  ]},
  {"3. Licencia" = "03-licencia.md"}
]

[project.theme]
language = "es"
variant = "modern"
logo = "assets/images/favicon.png"
favicon = "assets/images/favicon.png"
features = [
  "navigation.sections",
  "navigation.indexes",
  "navigation.path",
  "navigation.top",
  "navigation.footer",
  "toc.follow",
  "content.code.copy"
]

[project.theme.font]
text = "Open Sans"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "deep orange"
accent = "light blue"

[project.theme.palette.toggle]
icon = "material/weather-night"
name = "Cambiar a modo oscuro"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "deep orange"
accent = "light blue"

[project.theme.palette.toggle]
icon = "material/weather-sunny"
name = "Cambiar a modo claro"

[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
linenums_style = "pymdownx-inline"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
